#!/usr/bin/env bash
# vim: ft=sh

set -euo pipefail

mkdir -p ~/.tmp

export TMPDIR=~/.tmp

export AUTOUPDATE_USER="nmattia-autoupdate"
export AUTOUPDATE_EMAIL="nicolas@nmattia.com"
export AUTOUPDATE_NAME="Nicolas Mattia"
export REVIEW_USER="nmattia"

update_package() {
    dir=$(mktemp -d)

    cd $dir

    git clone "https://github.com/nmattia/$1"

    cd $1

    ./script/update 2>&1 > /dev/null || return 1

    if [[ `git status --porcelain` ]]; then

        date_tag=$(date --iso-8601)
        branch_name="autoupdate-$date_tag"
        git checkout -b "$branch_name"

        git config user.email "$AUTOUPDATE_EMAIL"
        git config user.name "$AUTOUPDATE_NAME"

        git commit --author="$AUTOUPDATE_NAME <$AUTOUPDATE_EMAIL>" -am "Update dependencies"

        hub fork 2>&1 >/dev/null

        git remote set-url \
            "$AUTOUPDATE_USER" \
            "https://${GITHUB_TOKEN}@github.com/$AUTOUPDATE_USER/$1.git" \
            2>&1 >/dev/null


        git push -fu "$AUTOUPDATE_USER" "$branch_name" 2>&1 >/dev/null

        hub pull-request \
            -m "Update dependencies" \
            -r "$REVIEW_USER" \
            2>&1 >/dev/null
    else
        echo "No updated for $1"
    fi
}

did_fail=0

update_package stutter || did_fail=1
update_package makefile || did_fail=1
update_package snack || did_fail=1
update_package snipcheck || did_fail=1
update_package nmattia.com || did_fail=1
update_package resume || did_fail=1
update_package niv || did_fail=1

exit $did_fail
